### ISSUE TITLE
Create transform rule with the attribute "<dn>"

### ISSUE THREAD

**Issue by VVincent0** [lithnet/umare#4]
Hello,

i would like to get the last element of the DN for an eDirectory referencial the attribute name is `<dn>`.

When i create advanced flow rule to import it (i use the Get DN component function) but the rule name is missparssed because it looks like this `<dn>>>GetDNComponent>>customAttributeDNComponent`, as you see there is 3 ">", is there a way to change the ">>" patern used to parse a flow rule name ?

Thank you

**Comment by ryannewington** [comment]
@VVincent0 ,

Just use `DN>>GetDNComponent>>customAttributeDNComponent`

Ryan

**Comment by VVincent0** [comment]
I tried this, unfortunately i have the error Attribute « <CS object dn> » is not declared as a dependency.

Vincent

De : Ryan Newington [mailto:notifications@github.com]
Envoyé : mardi 18 juillet 2017 23:03
À : lithnet/umare <umare@noreply.github.com>
Cc : VUILLAUME Vincent <vincentv@dsagency.fr>; Mention <mention@noreply.github.com>
Objet : Re: [lithnet/umare] Create transform rule with the attribute "<dn>" (#4)


@VVincent0<https://github.com/vvincent0> ,

Just use DN>>GetDNComponent>>customAttributeDNComponent

Ryan

**Comment by ryannewington** [comment]
@VVincent0 apologies for not replying, I must have missed the notification on this one. Did you manage to get the issue sorted out?
