### ISSUE TITLE
XPath query containing an apostrophe is not processed correctly

### ISSUE THREAD

**Issue by r3dlin3** [lithnet/umare#5]
I've tried to use an XML file lookup with a XML and a rule quite similar to example given in https://github.com/lithnet/transform-engine/wiki/XML-file-lookup

However, it does not work with single quote. I have tried:
- to use double quotes around {attributeValue}
- Single quotes around {attributeValue} but in my XML the character "'" replaced by "\&apos;"
- The same with double quotes
- Restart the editor each time to test

Using Visual Code to evaluate my XPath, it works

     XPath Query: //Fonction["VALUE WITH '" = @from]/@to
     [Line 20] to: XXX

I have the problem in the editor or in a full sync preview.

Not sure if it is a UMARE issue or transform.

**Comment by ryannewington** [comment]
@r3dlin3 can you send me a sample snipit of the XML that is failing so I can load it into my test framework

**Comment by ryannewington** [comment]
I think I've found the problem. Can you test this build?
[Lithnet.Umare.zip](https://github.com/lithnet/umare/files/1221293/Lithnet.Umare.zip)

**Comment by r3dlin3** [comment]
Works great for me.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/umare/releases/tag/v1.5.6435

**Comment by r3dlin3** [comment]
Thank you for this quick fix and enhancement. I have installed the latest version and it works :p
