### ISSUE TITLE
Values not present in source are simply omited from Transform arguments

### ISSUE THREAD

**Issue by sean-m** [lithnet/umare#9]
I'm trying to move an intricate display name population system from a standard rules extension to a UMARE transform rule. The rule expects this argument ordering: dhsNameFlg, sAMAccountName, displayName, initials, sn, givenName. dhsNameFlg is a bool that may be unset in AD and so IsPresent() == false so it is omitted from the list, I can simply check the type of element 0 to get around this but if in the case of a service account they never set the sn, or givenName I have no good way to tell if those are present in the list. Could you optionally place a null value for properties that aren't present? If you have some sense of where that change would need to be made could you point me in the right direction? I'd be happy to code it myself and send a PR.

**Comment by sean-m** [comment]
So after reading the source code, it appears that it's always functioned the way I would assume it should, GetSVAttributeValue returns false for boolean values that aren't present. I'm investigating further to see why that's not our observed behavior.

**Comment by ryannewington** [comment]
@sean-m what transform type are you using? Can you provide me your flow rule name.

**Comment by sean-m** [comment]
I'm using a C# script that is adapting what I had as an existing rule extension. Here's the flow rule name: dhsNameFlg+displayName+sAMAccountName+initials+sn+givenName+>>BuildDisplayName>>displayName . Here's the actual [script code](https://gist.github.com/sean-m/027559743c7dad89d1e0cd3cda058a35), sorry it's kind of a mess, I'm having to codify a strange naming standard. The dhsNameFlg is a bool on AD User, it's a hold over from a Perl/DB2 legacy sync system MIM is replacing.

**Comment by ryannewington** [comment]
@sean-m Apologies for the delay in getting back to you. I've been a bit swamped. Is this still and issue? I'm happy to work further on this with you if it is.

**Comment by sean-m** [comment]
No worries. It's me holding things up this time. I've pushed back on the business and display name is now a best effort. You can close the issue. If I ever circle back to it I'll let you know.
